[package]
name = "rakko-rust"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
rakko-action = { workspace = true }
rakko-build-internal-docs = { path = "../../actions/rakko-build-internal-docs", version = "0.1.0" }
rakko-check-dependencies = { path = "../../actions/rakko-check-dependencies", version = "0.1.0" }
rakko-check-latest-deps = { path = "../../actions/rakko-check-latest-deps", version = "0.1.0" }
rakko-check-unused-deps = { path = "../../actions/rakko-check-unused-deps", version = "0.1.0" }
rakko-format-rust = { path = "../../actions/rakko-format-rust", version = "0.1.0" }
rakko-lint-rust = { path = "../../actions/rakko-lint-rust", version = "0.1.0" }
rakko-test-rust = { path = "../../actions/rakko-test-rust", version = "0.1.0" }

[lints]
workspace = true
