//! Tests that run the set-msrv command against a project on disk
//!
//! Each test writes a root manifest and a `mise.toml` into a temporary
//! directory, runs the command there, and reads what the run left behind. A
//! test that gives the project a `mise.lock` runs the mise of the machine,
//! because mise writes its own lock.

// An assertion in a test panics by design, and the helpers of this file
// exist only for tests. The lints that guard production code do not apply.
#![allow(clippy::expect_used)]
#![allow(clippy::missing_errors_doc)]
#![allow(clippy::missing_panics_doc)]

use std::path::PathBuf;

use rakko_action::{Args, ArgsValues, ArgumentValue, Context, argument_name};
use rakko_cli::Command;
use rakko_cli::clawless::CommandResult;
use rakko_cli::clawless::context::Context as ClawlessContext;
use rakko_cli::clawless::event::event_channel;
use rakko_cli::clawless::prelude::Output;
use rakko_set_msrv::{SetMsrv, SetMsrvArgs, SetMsrvError};
use tempfile::TempDir;
use toml_edit::DocumentMut;

/// The manifest of a workspace whose members inherit the version
///
/// The comment of the version spans two lines, and a comment above a blank
/// line belongs to no key.
const WORKSPACE: &str = r#"[workspace]
members = ["a"]

[workspace.package]
edition = "2024"
# Every member inherits the fields below.

# bon 3.10 requires Rust 1.88
# or higher
rust-version = "1.88.0" # the floor

[workspace.dependencies]
bon = "3"
"#;

/// The manifest in [`WORKSPACE`] after a bump to 1.89.0
const BUMPED_WORKSPACE: &str = r#"[workspace]
members = ["a"]

[workspace.package]
edition = "2024"
# Every member inherits the fields below.

# bon 3.11 requires Rust 1.89
rust-version = "1.89.0" # the floor

[workspace.dependencies]
bon = "3"
"#;

/// The manifest of a package that belongs to no workspace
const PACKAGE: &str = r#"[package]
name = "otter"
edition = "2024"
# Kept low for the users of Debian
rust-version = "1.88.0"
"#;

/// The pins of a project that write each toolchain as a table
const TABLES: &str = r#"[tools]
# The first toolchain is the default.
rust = [
  { version = "1.98.1", components = [
    "clippy",
  ] },
  { version = "nightly-2026-08-11" },
  { version = "1.88.0", profile = "minimal" },
]
jq = "1.8.2"
"#;

/// The pins of a project that write each toolchain as text
const TEXTS: &str = "[tools]\nrust = [\"1.98.1\", \"1.88.0\"]\n";

/// The lock that mise writes for the pins in [`TEXTS`]
const LOCK: &str = r#"# @generated - this file is auto-generated by `mise lock` https://mise.jdx.dev/dev-tools/mise-lock.html

lockfile_version = 1

[[tools.rust]]
version = "1.98.1"
backend = "core:rust"
specifiers = ["1.98.1"]

[[tools.rust]]
version = "1.88.0"
backend = "core:rust"
specifiers = ["1.88.0"]
"#;

/// A project in a temporary directory, removed when the test ends
struct Project {
    /// The directory that holds the project
    directory: TempDir,
}

impl Project {
    /// Creates a project with a root manifest and a `mise.toml`
    fn new(manifest: &str, pins: &str) -> Self {
        let project = Self {
            directory: tempfile::tempdir().expect("the test creates a temporary directory"),
        };
        project.write("Cargo.toml", manifest);
        project.write("mise.toml", pins);

        project
    }

    /// Returns the path of a file of the project
    fn path(&self, file: &str) -> PathBuf {
        self.directory.path().join(file)
    }

    /// Returns the text of a file of the project
    fn read(&self, file: &str) -> String {
        std::fs::read_to_string(self.path(file)).expect("the test reads a file of the project")
    }

    /// Runs the command with the given arguments and returns its result
    async fn run(&self, msrv: &str, reason: &str) -> CommandResult {
        let args = SetMsrvArgs::from_values(&ArgsValues::new([
            (argument_name!("msrv"), ArgumentValue::new(msrv)),
            (argument_name!("reason"), ArgumentValue::new(reason)),
        ]))
        .expect("the test gives both arguments a value that they read");
        let project = Context::builder().root(self.directory.path()).build();
        let (sender, _receiver) = event_channel();
        let clawless = ClawlessContext::builder()
            .current_working_directory(self.directory.path())
            .output(Output::new(sender))
            .build()
            .expect("the test names a working directory");

        SetMsrv.run(&project, &clawless, &args).await
    }

    /// Runs the command to a bump from 1.88.0 to 1.89.0 and returns its error
    async fn fail(&self) -> SetMsrvError {
        self.run("1.89.0", "bon 3.11 requires Rust 1.89")
            .await
            .expect_err("the test expects the run to fail")
            .downcast()
            .expect("the run fails with an error of the command")
    }

    /// Writes a file of the project
    fn write(&self, file: &str, text: &str) {
        std::fs::write(self.path(file), text).expect("the test writes a file of the project");
    }
}

/// Returns each Rust toolchain that a lock holds, as its version and the
/// text of its specifiers, sorted
///
/// Mise decides the order of the entries in its lock, so the entries are
/// sorted to keep a test independent of that order. The specifiers show
/// whether mise rewrote an entry that the run did not move.
fn locked(lock: &str) -> Vec<(String, String)> {
    let lock: DocumentMut = lock.parse().expect("mise writes a lock that parses");

    let mut toolchains: Vec<(String, String)> = lock["tools"]["rust"]
        .as_array_of_tables()
        .expect("the lock holds the Rust toolchains")
        .iter()
        .map(|toolchain| {
            (
                toolchain["version"].to_string().trim().to_owned(),
                toolchain["specifiers"].to_string().trim().to_owned(),
            )
        })
        .collect();
    toolchains.sort();

    toolchains
}

// A root that is a package and a workspace at once inherits the version of
// the workspace, so the version of the workspace is the one to change.
// setmsrv[verify manifest.version]
#[tokio::test]
async fn run_in_a_package_of_a_workspace_sets_the_version_of_the_workspace() {
    let project = Project::new(
        "[package]\nname = \"otter\"\nrust-version.workspace = true\n\n[workspace.package]\nrust-version = \"1.88.0\"\n",
        TEXTS,
    );

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("Cargo.toml"),
        "[package]\nname = \"otter\"\nrust-version.workspace = true\n\n[workspace.package]\n# bon 3.11 requires Rust 1.89\nrust-version = \"1.89.0\"\n"
    );
}

// setmsrv[verify manifest.version]
// setmsrv[verify manifest.comment]
#[tokio::test]
async fn run_in_a_package_sets_the_version_of_the_package() {
    let project = Project::new(PACKAGE, TEXTS);

    project
        .run("1.89.0", "Kept low for the users of Debian 13")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("Cargo.toml"),
        r#"[package]
name = "otter"
edition = "2024"
# Kept low for the users of Debian 13
rust-version = "1.89.0"
"#
    );
}

// setmsrv[verify manifest.version]
// setmsrv[verify manifest.comment]
// setmsrv[verify files.layout]
#[tokio::test]
async fn run_in_a_workspace_sets_the_version_and_its_comment() {
    let project = Project::new(WORKSPACE, TEXTS);

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(project.read("Cargo.toml"), BUMPED_WORKSPACE);
}

// A workspace that declares no version leaves the version of the package in
// charge.
// setmsrv[verify manifest.version]
#[tokio::test]
async fn run_in_a_workspace_without_a_version_sets_the_version_of_the_package() {
    let project = Project::new(
        "[package]\nname = \"otter\"\nrust-version = \"1.88.0\"\n\n[workspace.package]\nedition = \"2024\"\n",
        TEXTS,
    );

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("Cargo.toml"),
        "[package]\nname = \"otter\"\n# bon 3.11 requires Rust 1.89\nrust-version = \"1.89.0\"\n\n[workspace.package]\nedition = \"2024\"\n"
    );
}

// setmsrv[verify files.layout]
#[tokio::test]
async fn run_on_files_that_end_lines_with_carriage_returns_keeps_them() {
    let project = Project::new(&WORKSPACE.replace('\n', "\r\n"), TEXTS);

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("Cargo.toml"),
        BUMPED_WORKSPACE.replace('\n', "\r\n")
    );
}

// setmsrv[verify pin.version]
#[tokio::test]
async fn run_sets_a_single_pin() {
    let project = Project::new(WORKSPACE, "[tools]\nrust = \"1.88.0\"\n");

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(project.read("mise.toml"), "[tools]\nrust = \"1.89.0\"\n");
}

// A project whose default toolchain is its MSRV pins the version twice. The
// first pin is the default, and it stays.
// setmsrv[verify pin.version]
#[tokio::test]
async fn run_sets_the_last_matching_pin() {
    let project = Project::new(WORKSPACE, "[tools]\nrust = [\"1.88.0\", \"1.88.0\"]\n");

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("mise.toml"),
        "[tools]\nrust = [\"1.88.0\", \"1.89.0\"]\n"
    );
}

// setmsrv[verify pin.version]
#[tokio::test]
async fn run_sets_the_matching_pin_of_an_array_of_tables() {
    let project = Project::new(
        WORKSPACE,
        "[[tools.rust]]\nversion = \"1.98.1\"\n\n[[tools.rust]]\nversion = \"1.88.0\"\n",
    );

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("mise.toml"),
        "[[tools.rust]]\nversion = \"1.98.1\"\n\n[[tools.rust]]\nversion = \"1.89.0\"\n"
    );
}

// setmsrv[verify pin.version]
// setmsrv[verify files.layout]
#[tokio::test]
async fn run_sets_the_matching_pin_of_tables() {
    let project = Project::new(WORKSPACE, TABLES);

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("mise.toml"),
        TABLES.replace(
            r#"{ version = "1.88.0", profile = "minimal" }"#,
            r#"{ version = "1.89.0", profile = "minimal" }"#
        )
    );
}

// setmsrv[verify pin.version]
#[tokio::test]
async fn run_sets_the_matching_pin_of_texts() {
    let project = Project::new(WORKSPACE, TEXTS);

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("mise.toml"),
        "[tools]\nrust = [\"1.98.1\", \"1.89.0\"]\n"
    );
}

// setmsrv[verify pin.version]
#[tokio::test]
async fn run_sets_the_pin_of_a_table() {
    let project = Project::new(WORKSPACE, "[tools.rust]\nversion = \"1.88.0\"\n");

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        project.read("mise.toml"),
        "[tools.rust]\nversion = \"1.89.0\"\n"
    );
}

// setmsrv[verify lock.failed]
#[tokio::test]
async fn run_whose_mise_refuses_to_lock_reports_what_mise_said() {
    let project = Project::new(WORKSPACE, &format!("min_version = \"9999.0.0\"\n\n{TEXTS}"));
    project.write("mise.lock", LOCK);

    let error = project.fail().await;

    assert!(matches!(
        error,
        SetMsrvError::UnlockedPin { details } if details.contains("9999.0.0")
    ));
}

// setmsrv[verify lock.update]
#[tokio::test]
async fn run_with_a_lock_locks_the_new_pin() {
    let project = Project::new(WORKSPACE, TEXTS);
    project.write("mise.lock", LOCK);

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert_eq!(
        locked(&project.read("mise.lock")),
        [
            ("\"1.89.0\"".to_owned(), "[\"1.89.0\"]".to_owned()),
            ("\"1.98.1\"".to_owned(), "[\"1.98.1\"]".to_owned()),
        ]
    );
}

// setmsrv[verify files.unreadable]
#[tokio::test]
async fn run_with_a_malformed_manifest_names_it() {
    let project = Project::new("[package\n", TEXTS);

    let error = project.fail().await;

    assert_eq!(
        error.to_string(),
        format!("failed to parse {}", project.path("Cargo.toml").display())
    );
}

// setmsrv[verify files.unreadable]
#[tokio::test]
async fn run_with_a_malformed_mise_toml_names_it() {
    let project = Project::new(WORKSPACE, "[tools\n");

    let error = project.fail().await;

    assert_eq!(
        error.to_string(),
        format!("failed to parse {}", project.path("mise.toml").display())
    );
}

// setmsrv[verify manifest.inline]
#[tokio::test]
async fn run_with_a_version_in_an_inline_table_names_the_manifest() {
    let project = Project::new(
        "[workspace]\npackage = { rust-version = \"1.88.0\" }\n",
        TEXTS,
    );

    let error = project.fail().await;

    assert_eq!(
        error.to_string(),
        format!(
            "{} declares rust-version in an inline table, which cannot hold the reason",
            project.path("Cargo.toml").display()
        )
    );
}

// setmsrv[verify manifest.undeclared]
#[tokio::test]
async fn run_without_a_declared_version_names_the_manifest() {
    let project = Project::new("[package]\nname = \"otter\"\n", TEXTS);

    let error = project.fail().await;

    assert_eq!(
        error.to_string(),
        format!(
            "{} declares no rust-version",
            project.path("Cargo.toml").display()
        )
    );
}

// setmsrv[verify lock.absent]
#[tokio::test]
async fn run_without_a_lock_creates_none() {
    let project = Project::new(WORKSPACE, TEXTS);

    project
        .run("1.89.0", "bon 3.11 requires Rust 1.89")
        .await
        .expect("the run succeeds");

    assert!(!project.path("mise.lock").exists());
}

// setmsrv[verify pin.unmatched]
#[tokio::test]
async fn run_without_a_matching_pin_changes_no_file() {
    let project = Project::new(WORKSPACE, "[tools]\nrust = \"1.98.1\"\n");

    let _error = project.fail().await;

    assert_eq!(
        (project.read("Cargo.toml"), project.read("mise.toml")),
        (
            WORKSPACE.to_owned(),
            "[tools]\nrust = \"1.98.1\"\n".to_owned()
        )
    );
}

// setmsrv[verify pin.unmatched]
#[tokio::test]
async fn run_without_a_matching_pin_names_the_version() {
    let project = Project::new(WORKSPACE, "[tools]\nrust = \"1.98.1\"\n");

    let error = project.fail().await;

    assert_eq!(
        error.to_string(),
        "mise.toml pins no Rust toolchain at 1.88.0, the current rust-version"
    );
}

// setmsrv[verify files.unreadable]
#[tokio::test]
async fn run_without_a_mise_toml_changes_no_file() {
    let project = Project::new(WORKSPACE, TEXTS);
    std::fs::remove_file(project.path("mise.toml")).expect("the test removes the pins");

    let _error = project.fail().await;

    assert_eq!(project.read("Cargo.toml"), WORKSPACE);
}

// setmsrv[verify files.unreadable]
#[tokio::test]
async fn run_without_a_mise_toml_names_it() {
    let project = Project::new(WORKSPACE, TEXTS);
    std::fs::remove_file(project.path("mise.toml")).expect("the test removes the pins");

    let error = project.fail().await;

    assert_eq!(
        error.to_string(),
        format!("failed to read {}", project.path("mise.toml").display())
    );
}
